### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Kgatishi** [DannR11/DiGital-BlackSmiths#1]
List members of our team showing current position, interests, skills and attitudes. A link to other profiles such a a git profile or LinkedIn profile; should have the basic information readily available on the landing page.

**Comment by olwabott** [comment]
I'll need everyone to post their  current positions, interests, skills and attitudes so I can include them on the landing page. I'll only add links to the git or linked in profiles if everybody agrees that that's what they want.

**Comment by NtlatlengL** [comment]
do you want the response here or in slack?

**Comment by olwabott** [comment]
In Slack is fine
