### ISSUE TITLE
6 Architectural diagram | Lesego

### ISSUE THREAD

**Issue by DannR11** [DannR11/DiGital-BlackSmiths#14]

**Comment by LesegoGomolemo** [comment]
[architecture deployment.pdf](https://github.com/DannR11/DiGital-BlackSmiths/files/1871216/architecture.deployment.pdf)

**Comment by LesegoGomolemo** [comment]
Architectural Diagram requires finished subsystems to be specified, for all three tiers, but we can expect those to be done.
